services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - 5432:5432
  
  redis:
    image: redis
    ports:
      - 6379:6379