GET http://localhost:3000/brand
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsdWNhc2RhbGFuMDlAZ21haWwuY29tIiwibmFtZSI6Ikx1Y2FzIERhbGFuIiwiaWF0IjoxNzE5ODM2MTU3fQ.hA1-exbyO_DdRaxw5jFkz2N-YuZG4Z8e-SwFeuo62hM

###

GET http://localhost:3000/brand/4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsdWNhc2RhbGFuMDlAZ21haWwuY29tIiwibmFtZSI6Ikx1Y2FzIERhbGFuIiwiaWF0IjoxNzE5ODM2MTU3fQ.hA1-exbyO_DdRaxw5jFkz2N-YuZG4Z8e-SwFeuo62hM

###

POST http://localhost:3000/brand
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsdWNhc2RhbGFuMDlAZ21haWwuY29tIiwibmFtZSI6Ikx1Y2FzIERhbGFuIiwiaWF0IjoxNzE5ODM2MTU3fQ.hA1-exbyO_DdRaxw5jFkz2N-YuZG4Z8e-SwFeuo62hM

{
  "code": 10,
  "description": "DALO"
}

###

PUT http://localhost:3000/brand/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsdWNhc2RhbGFuMDlAZ21haWwuY29tIiwibmFtZSI6Ikx1Y2FzIERhbGFuIiwiaWF0IjoxNzE5ODM2MTU3fQ.hA1-exbyO_DdRaxw5jFkz2N-YuZG4Z8e-SwFeuo62hM

{
  "description": "GA milicias"
}

###

DELETE http://localhost:3000/brand/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsdWNhc2RhbGFuMDlAZ21haWwuY29tIiwibmFtZSI6Ikx1Y2FzIERhbGFuIiwiaWF0IjoxNzE5ODM2MTU3fQ.hA1-exbyO_DdRaxw5jFkz2N-YuZG4Z8e-SwFeuo62hM
