GET http://localhost:3000/brand
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJiYXRvQGhhcm1vbml0LmNvbSIsIm5hbWUiOiJiYXRvIiwiaWF0IjoxNzE5ODQwNjY3fQ.tWwXUZWm4ucBMJXCIbOOLdwCeF3CoWXFok2orkFCzH8

###

GET http://localhost:3000/brand/5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJiYXRvQGhhcm1vbml0LmNvbSIsIm5hbWUiOiJiYXRvIiwiaWF0IjoxNzE5ODQwNjY3fQ.tWwXUZWm4ucBMJXCIbOOLdwCeF3CoWXFok2orkFCzH8

###

POST http://localhost:3000/brand
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJiYXRvQGhhcm1vbml0LmNvbSIsIm5hbWUiOiJiYXRvIiwiaWF0IjoxNzE5ODQwNjY3fQ.tWwXUZWm4ucBMJXCIbOOLdwCeF3CoWXFok2orkFCzH8

{
  "code": 10,
  "description": "marca beto"
}

###

PUT http://localhost:3000/brand/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJiYXRvQGhhcm1vbml0LmNvbSIsIm5hbWUiOiJiYXRvIiwiaWF0IjoxNzE5ODQwNjY3fQ.tWwXUZWm4ucBMJXCIbOOLdwCeF3CoWXFok2orkFCzH8

{
  "description": "GA milicias"
}

###

DELETE http://localhost:3000/brand/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJiYXRvQGhhcm1vbml0LmNvbSIsIm5hbWUiOiJiYXRvIiwiaWF0IjoxNzE5ODQwNjY3fQ.tWwXUZWm4ucBMJXCIbOOLdwCeF3CoWXFok2orkFCzH8
