GET http://localhost:3000/product
Content-Type: application/json

###

GET http://localhost:3000/product/1
Content-Type: application/json

###

POST http://localhost:3000/product
Content-Type: application/json

{
  "code": 10,
  "name": "Não",
  "price": 57.100000000,
  "userId": 5,
  "brandId": 3
}

###

PUT http://localhost:3000/product/1
Content-Type: application/json

{
  "name": "Facão do GA"
}

###

DELETE http://localhost:3000/product/2
Content-Type: application/json