GET http://localhost:3000/product
Content-Type: application/json

###

GET http://localhost:3000/product/1
Content-Type: application/json

###

POST http://localhost:3000/product
Content-Type: application/json

{
  "code": 3,
  "name": "Laranja do GA",
  "price": 57.10,
  "userId": 3,
  "brandId": 2
}

###

PUT http://localhost:3000/product/1
Content-Type: application/json

{
  "name": "Facão do GA"
}

###

DELETE http://localhost:3000/product/3
Content-Type: application/json